### ISSUE TITLE
Getting an error...

### ISSUE THREAD

**Issue by lblanchardiii** [Dan-Levi/wpbridge-rust#1]
Got the plugin loaded on both the WP site (new install) and in Rust (my test server)

Generated the key, edited the json file on the rust server

https://rustalaxy.com/ is the URL entered in the json as well as the location of the site it's installed.

Getting this error when attempting to load plugin on the rust server.

(20:37:37) | Loaded plugin WPBridge v0.0.2 by Murky
(20:37:38) | [WPBridge] [DEBUG] External IP is **IPMASKEDFORPRIVACY**
(20:37:38) | [WPBridge] [DEBUG] Configuration validated.
(20:37:38) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>404 Not Found</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">404</div>
    <h2>Page Not Found</h2>
    <p class="lead">This page either doesn't exist, or it moved somewhere else.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>
(20:37:38) | Unloaded plugin WPBridge v0.0.2 by Murky
(20:37:38) | Web request callback raised an exception in 'WPBridge v0.0.2' plugin (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.)
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Oxide.Plugins.WPBridge.<ValidateSecret>m__1 (System.Int32 responseCode, System.String responseString) [0x00032] in <9f5d97d2da2444db8f8058253ba4af09>:0 
  at Oxide.Core.Libraries.WebRequests+WebRequest.<OnComplete>b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0

**Comment by Dan-Levi** [comment]
Hi, Thanks for letting me know. I have just pushed an update out. Please delete the config file that is generated and overwrite the plugin with the updated one from here: https://github.com/Dan-Levi/wpbridge-rust Let me know if there are any other issues you are experiencing. Sendt fra E-post for Windows Fra: lblanchardiiiSendt: lørdag 2. oktober 2021 kl. 02:41Til: Dan-Levi/wpbridge-rustKopi: SubscribedEmne: [Dan-Levi/wpbridge-rust] Getting an error... (#1) Got the plugin loaded on both the WP site (new install) and in Rust (my test server)Generated the key, edited the json file on the rust serverhttps://rustalaxy.com/ is the URL entered in the json as well as the location of the site it's installed.Getting this error when attempting to load plugin on the rust server.(20:37:37) | Loaded plugin WPBridge v0.0.2 by Murky(20:37:38) | [WPBridge] [DEBUG] External IP is IPMASKEDFORPRIVACY(20:37:38) | [WPBridge] [DEBUG] Configuration validated.(20:37:38) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <title>404 Not Found</title> Server Error404Page Not FoundThis page either doesn't exist, or it moved somewhere else.That's what you can doReload Page Back to Previous Page Home Page (20:37:38) | Unloaded plugin WPBridge v0.0.2 by Murky (20:37:38) | Web request callback raised an exception in 'WPBridge v0.0.2' plugin (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Oxide.Plugins.WPBridge.m__1 (System.Int32 responseCode, System.String responseString) [0x00032] in <9f5d97d2da2444db8f8058253ba4af09>:0 at Oxide.Core.Libraries.WebRequests+WebRequest.b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lblanchardiii** [comment]
Yes, still the same error.

Deleted the .CS file and the .json file from server. Uploaded the new .CS file and edited the new .json (I see you have to enter external IP manually now) and the error is still the same.

(11:21:23) | [WPBridge] [DEBUG] Configuration validated.
(11:21:23) | Loaded plugin WPBridge v0.0.2 by Murky
(11:21:24) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>404 Not Found</title>
  <link rel="stylesheet" href="/error_docs/styles.css">
</head>
<body>
<div class="page">
  <div class="main">
    <h1>Server Error</h1>
    <div class="error-code">404</div>
    <h2>Page Not Found</h2>
    <p class="lead">This page either doesn't exist, or it moved somewhere else.</p>
    <hr/>
    <p>That's what you can do</p>
    <div class="help-actions">
      <a href="javascript:location.reload();">Reload Page</a>
      <a href="javascript:history.back();">Back to Previous Page</a>
      <a href="/">Home Page</a>
    </div>
  </div>
</div>
</body>
</html>
(11:21:24) | Unloaded plugin WPBridge v0.0.2 by Murky
(11:21:24) | Web request callback raised an exception (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.)
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 
  at Oxide.Plugins.WPBridge.<ValidateSecret>m__0 (System.Int32 responseCode, System.String responseString) [0x00032] in <500530faa9e849f9bc8d16457e761f53>:0 
  at Oxide.Core.Libraries.WebRequests+WebRequest.<OnComplete>b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0

**Comment by Dan-Levi** [comment]
Do you have discord?You can add me there: Murky#9929   Sendt fra E-post for Windows Fra: lblanchardiiiSendt: lørdag 2. oktober 2021 kl. 17:23Til: Dan-Levi/wpbridge-rustKopi: Dan-Levi Tømta; State changeEmne: Re: [Dan-Levi/wpbridge-rust] Getting an error... (#1) Yes, still the same error.Deleted the .CS file and the .json file from server. Uploaded the new .CS file and edited the new .json (I see you have to enter external IP manually now) and the error is still the same.(11:21:23) | [WPBridge] [DEBUG] Configuration validated.(11:21:23) | Loaded plugin WPBridge v0.0.2 by Murky(11:21:24) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <title>404 Not Found</title> Server Error404Page Not FoundThis page either doesn't exist, or it moved somewhere else.That's what you can doReload Page Back to Previous Page Home Page (11:21:24) | Unloaded plugin WPBridge v0.0.2 by Murky (11:21:24) | Web request callback raised an exception (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Oxide.Plugins.WPBridge.m__0 (System.Int32 responseCode, System.String responseString) [0x00032] in <500530faa9e849f9bc8d16457e761f53>:0 at Oxide.Core.Libraries.WebRequests+WebRequest.b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0 —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dan-Levi** [comment]
There seem to be something with the WordPress Rest API, because it is not accessible on https://rustalaxy.com/wp-json/wpbridge/secret If you try https://wpbridge.danlevi.no/wp-json/wpbridge/secret you can see that the wp-json is accessible.If you create an admin user for me you can delete later i can have a look at it. Sendt fra E-post for Windows Fra: lblanchardiiiSendt: lørdag 2. oktober 2021 kl. 02:41Til: Dan-Levi/wpbridge-rustKopi: SubscribedEmne: [Dan-Levi/wpbridge-rust] Getting an error... (#1) Got the plugin loaded on both the WP site (new install) and in Rust (my test server)Generated the key, edited the json file on the rust serverhttps://rustalaxy.com/ is the URL entered in the json as well as the location of the site it's installed.Getting this error when attempting to load plugin on the rust server.(20:37:37) | Loaded plugin WPBridge v0.0.2 by Murky(20:37:38) | [WPBridge] [DEBUG] External IP is IPMASKEDFORPRIVACY(20:37:38) | [WPBridge] [DEBUG] Configuration validated.(20:37:38) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <title>404 Not Found</title> Server Error404Page Not FoundThis page either doesn't exist, or it moved somewhere else.That's what you can doReload Page Back to Previous Page Home Page (20:37:38) | Unloaded plugin WPBridge v0.0.2 by Murky (20:37:38) | Web request callback raised an exception in 'WPBridge v0.0.2' plugin (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Oxide.Plugins.WPBridge.m__1 (System.Int32 responseCode, System.String responseString) [0x00032] in <9f5d97d2da2444db8f8058253ba4af09>:0 at Oxide.Core.Libraries.WebRequests+WebRequest.b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dan-Levi** [comment]
Please try again now. Sendt fra E-post for Windows Fra: lblanchardiiiSendt: lørdag 2. oktober 2021 kl. 17:23Til: Dan-Levi/wpbridge-rustKopi: Dan-Levi Tømta; State changeEmne: Re: [Dan-Levi/wpbridge-rust] Getting an error... (#1) Yes, still the same error.Deleted the .CS file and the .json file from server. Uploaded the new .CS file and edited the new .json (I see you have to enter external IP manually now) and the error is still the same.(11:21:23) | [WPBridge] [DEBUG] Configuration validated.(11:21:23) | Loaded plugin WPBridge v0.0.2 by Murky(11:21:24) | [WPBridge] [500] -> Failed to deserialize Wordpress response: <title>404 Not Found</title> Server Error404Page Not FoundThis page either doesn't exist, or it moved somewhere else.That's what you can doReload Page Back to Previous Page Home Page (11:21:24) | Unloaded plugin WPBridge v0.0.2 by Murky (11:21:24) | Web request callback raised an exception (JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x00043] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <2ae3f091decd4989b3c4d466e6eb5985>:0 at Oxide.Plugins.WPBridge.m__0 (System.Int32 responseCode, System.String responseString) [0x00032] in <500530faa9e849f9bc8d16457e761f53>:0 at Oxide.Core.Libraries.WebRequests+WebRequest.b__42_0 () [0x00034] in <0fbce81d88d64454b3e7abb24df7026b>:0 —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
